<main role="main" class="container">

    <div class="my-3 p-3 bg-white rounded box-shadow">
        <h4 class="border-bottom border-dark pb-2 mb-0">Certificate Details</h4>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                ISIN<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getIsin()) ?></strong>
            </p>
        </div>
    </div>

    <div class="my-3 p-3 bg-white rounded box-shadow">
        <h4 class="border-bottom border-dark pb-2 mb-0">Trading Market</h4>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Name<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getTradingMarket()->getName()) ?></strong>
            </p>
        </div>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Phone<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getTradingMarket()->getPhone()) ?></strong>
            </p>
        </div>
    </div>

    <div class="my-3 p-3 bg-white rounded box-shadow">
        <h4 class="border-bottom border-dark pb-2 mb-0">Currency</h4>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Name<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getCurrency()->getName()) ?></strong>
            </p>
        </div>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Symbol<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getCurrency()->getSymbol()) ?></strong>
            </p>
        </div>
    </div>

    <div class="my-3 p-3 bg-white rounded box-shadow">
        <h4 class="border-bottom border-dark pb-2 mb-0">Issuer</h4>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Name<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getIssuer()->getName()) ?></strong>
            </p>
        </div>
    </div>

    <div class="my-3 p-3 bg-white rounded box-shadow">
        <h4 class="border-bottom border-dark pb-2 mb-0">Issuing Price</h4>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Amount<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getPrices()['issuing_price']->getAmount()) ?></strong>
            </p>
        </div>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Currency Name<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getPrices()['issuing_price']->getCurrency()->getName()) ?></strong>
            </p>
        </div>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Currency Symbol<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getPrices()['issuing_price']->getCurrency()->getSymbol()) ?></strong>
            </p>
        </div>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Date/Time<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getPrices()['issuing_price']->getTimestamp()) ?></strong>
            </p>
        </div>
    </div>

    <div class="my-3 p-3 bg-white rounded box-shadow">
        <h4 class="border-bottom border-dark pb-2 mb-0">Current Price</h4>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Amount<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getPrices()['current_price']->getAmount()) ?></strong>
            </p>
        </div>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Currency Name<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getPrices()['current_price']->getCurrency()->getName()) ?></strong>
            </p>
        </div>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Currency Symbol<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getPrices()['current_price']->getCurrency()->getSymbol()) ?></strong>
            </p>
        </div>
        <div class="media text-muted pt-3">
            <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
                Date/Time<strong class="d-block text-gray-dark"><?= $this->escapeHtml($this->certificate->getPrices()['current_price']->getTimestamp()) ?></strong>
            </p>
        </div>
    </div>

</main>
