<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to<br>Our Certificates Project</h1>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header">Certificates</h2>
        <div class="card-body">

            <p>
                <?= var_dump($this->certificates);die(); ?>
            </p>

        </div>
    </div>
</div>
