<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to<br>Our Certificates Project</h1>
</div>

<div class="row">
    <?php foreach ($this->certificates as $certificate): ?>
        <div class="col-md-4">
            <h2 class="card-header"><?= $certificate->getIsin() ?></h2>
            <div class="card-body">
                <p>
                    <a class="btn btn-primary"
                       href="<?= $this->url('certificate/html', ['isin' => $certificate->getIsin()]) ?>"
                       target="_blank">
                        HTML &raquo;
                    </a>
                    <a class="btn btn-danger"
                       href="<?= $this->url('certificate/xml', ['isin' => $certificate->getIsin()]) ?>"
                       target="_blank">
                        XML &raquo;
                    </a>
                </p>
            </div>
        </div>
    <?php endforeach ?>
</div>
